# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
reviews:
  poem: false
  auto_review:
    enabled: false
    auto_incremental_review: false
  review_status: false
  commit_status: false
chat:
  auto_reply: false
