spring:
  application:
    name: "travlocks"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}

mail:
  resend:
    api-key: ${RESEND_API_KEY}
    from-email: ${RESEND_FROM_EMAIL}

jwt:
  secret: ${JWT_SECRET:}
  access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600} # 1시간
  refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:1209600} # 14일

app:
  profile:
    default-base-url: ${DEFAULT_PROFILE_BASE_URL:https://travlocks-bucket.s3.ap-northeast-2.amazonaws.com/profiles/defaults}
    default-files: ${DEFAULT_PROFILE_FILES:amaze.svg,happy.svg,normal.svg,playful.svg,sad.svg,wink.png}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

suggestion:
  vlock:
    size: 3
    min-pool: 50
    popular-pool: 100  # Day에 있는 Vlock이 0개일 때 DB에서 가져올 Vlock의 최대 추천 후보 수
    box-pool: 300
    pool-size: 30
    ai-candidate-pool: 40
    max-duplicate-category: 2

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  base-url: https://dapi.kakao.com
  keyword-search:
    path: /v2/local/search/keyword.json
    size: 15
  timeout:
    connect-ms: 1000
    response-ms: 3000

hyperclova:
  base-url: https://clovastudio.stream.ntruss.com/v1/chat-completions/{model}
  api-key: ${CLOVA_API_KEY}
  model: HCX-003
  timeout-ms:
    connect: 2000
    response: 6000
  retry:
    max: 2
    backoff-ms: 200

cache:
  recommendation:
    templates:
      cache-ttl-minutes: 15
    vlocks:
      cache-ttl-minutes: 60

tmap:
  api:
    key: ${TMAP_API_KEY}
    base-url: ${TMAP_BASE_URL:https://apis.openapi.sk.com}