spring:
  application:
    name: "travlocks"
  profiles:
    active: benchmark


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true

  logging:
    level:
      org.hibernate.SQL: WARN
      org.hibernate.orm.jdbc.bind: OFF

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: travlocks-bucket
    domain: ${DEFAULT_S3_BASE_URL:https://travlocks-bucket.s3.ap-northeast-2.amazonaws.com/}

mail:
  resend:
    api-key: ${RESEND_API_KEY}
    from-email: ${RESEND_FROM_EMAIL}

jwt:
  secret: ${JWT_SECRET:}
  access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600} # 1시간
  refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:1209600} # 14일

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI:https://www.travlocks.com/naver/callback}
    token-uri: https://nid.naver.com/oauth2.0/token
    userinfo-uri: https://openapi.naver.com/v1/nid/me

password-reset:
  redirect-uri: ${PASSWORD_RESET_REDIRECT_URI:https://www.travlocks.com/password-reset}
  ttl-minutes: ${PASSWORD_RESET_TTL_MINUTES:5}

app:
  profile:
    default-base-url: ${DEFAULT_PROFILE_BASE_URL:https://travlocks-bucket.s3.ap-northeast-2.amazonaws.com/profiles/defaults}
    default-files: ${DEFAULT_PROFILE_FILES:amaze.svg,happy.svg,normal.svg,playful.svg,sad.svg,wink.png}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

suggestion:
  vlock:
    size: 3
    min-pool: 50
    popular-pool: 30  # Day에 있는 Vlock이 0개일 때 DB에서 가져올 Vlock의 최대 추천 후보 수
    box-pool: 300
    pool-size: 30
    ai-candidate-pool: 40
    max-duplicate-category: 2

tag:
  cron: "0 5 * * * *"
  grace-minutes: 15
  lookback-minutes: 75

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  base-url: https://dapi.kakao.com
  keyword-search:
    path: /v2/local/search/keyword.json
    size: 15
  timeout:
    connect-ms: 1000
    response-ms: 3000

hyperclova:
  base-url: https://clovastudio.stream.ntruss.com/v1/chat-completions/{model}
  api-key: ${CLOVA_API_KEY}
  model: HCX-003
  timeout-ms:
    connect: 2000
    response: 6000
  retry:
    max: 2
    backoff-ms: 200

cache:
  suggestion:
    templates:
      cache-ttl-minutes: 15
    vlocks:
      cache-ttl-minutes: 60
  categories:
    cache-ttl-minutes: 1440

template:
  limit:
    recent: 5
    suggestion: 10

tmap:
  api:
    key: ${TMAP_API_KEY}
    base-url: ${TMAP_BASE_URL:https://apis.openapi.sk.com}

sse:
  timeout-ms: 3600000  # 1시간
  heartbeat-ms: 30000  # 30초

cookie:
  sse-token:
    name: SSE_TOKEN
    path: /api/v1/notifications
    token-ttl-ms: 1800000 # 30분
    same-site: None
    secure: true
    http-only: true  # 로컬 http면 false, 운영 https면 true

global:
  timezone: Asia/Seoul
