drop table if exists move_times;
drop table if exists vlocks;
drop table if exists vlock_categories;
drop table if exists cities;
drop table if exists regions;

create table regions (
	region_id bigint not null,
	name varchar(10) not null,
	created_at timestamp not null,
	updated_at timestamp,
	deleted_at timestamp,
	primary key (region_id)
);

create table cities (
	city_id bigint not null,
	region_id bigint not null,
	name varchar(10) not null,
	created_at timestamp not null,
	updated_at timestamp,
	deleted_at timestamp,
	primary key (city_id)
);

create table vlock_categories (
	vlock_category_id bigint not null,
	name varchar(10) not null,
	stay_hours double precision not null,
	default_creation_image_key varchar(255) not null,
	default_category_image_key varchar(255) not null,
	created_at timestamp not null,
	deleted_at timestamp,
	primary key (vlock_category_id)
);

create table vlocks (
	vlock_id bigint generated by default as identity,
	external_place_unique varchar(255),
	external_place_id varchar(255),
	vlock_category_id bigint not null,
	city_id bigint not null,
	owner_id bigint,
	name varchar(30) not null,
	cover_img_url varchar(255),
	latitude double precision not null,
	longitude double precision not null,
	address varchar(255) not null,
	memo varchar(200),
	usage_count integer not null,
	is_public boolean not null,
	created_at timestamp not null,
	updated_at timestamp,
	deleted_at timestamp,
	primary key (vlock_id)
);

create table move_times (
	move_times_id bigint generated by default as identity,
	from_vlock_id bigint not null,
	to_vlock_id bigint not null,
	move_minutes integer not null,
	transport_type varchar(10) not null,
	distance_meter integer not null,
	polyline text,
	created_at timestamp not null,
	updated_at timestamp,
	primary key (move_times_id)
);

create index idx_move_times_route on move_times (from_vlock_id, to_vlock_id, transport_type);
